namespace: ansible
name: layer3
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.netcommon: '>=1.0'
repository: git@github.com:ansible-collection-migration/ansible.layer3.git
documentation: https://github.com/ansible-collection-migration/ansible.layer3/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.layer3
issues: https://github.com/ansible-collection-migration/ansible.layer3/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
